### PR TITLE
Feature Richmenu util

### PR DESCRIPTION
**Pull request by tnuanchuay**

### CODE REVIEW

**Comment by tnuanchuay** [comment]
@imkk-000 Please review it. this is ready to go

**Review by imkk000 — COMMENTED** [review]
I understanded all of code, but I think richmenu_wrapper shouldn't have all mock. Because of mock made for test, they should move to richmenu_wrapper_test.go. What you think about my opinion?

**Comment by tnuanchuay** [comment]
@imkk-000 changed, mock type in `richmenu_wrapper` has been moved to its file `richmenu_wrapper_mock`

**Comment by imkk000** [comment]
@tspn Okay.

**Pull request merged**
